apiVersion: v1
kind: List
metadata: {}
items:
######################################################################
# Gerrit
######################################################################
- apiVersion: v1
  kind: Service
  metadata:
    name: gerrit
  spec:
    ports:
    - name: http
      port: 8080
    - name: ssh
      port: 29418
    selector:
      service: gerrit

- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      service: gerrit
    name: gerrit
  spec:
    replicas: 1
    selector:
      matchLabels:
        service: gerrit
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          service: gerrit
      spec:
        restartPolicy: Always
        nodeSelector:
          cicd-svc-gerrit: "true"

        containers:
        - image: repository.azurecr.cn/gerrit:latest
          name: gerrit
          envFrom:
          - configMapRef:
              name: config-env
          env:
          - name: GERRIT_INIT_ARGS
            value: --install-plugin=download-commands --install-plugin=replication
          - name: GITWEB_TYPE
            value: gitiles
          - name: HTTPD_LISTENURL
            value: proxy-http://*:8080
          - name: WEBURL
            value: "https://gerrit.$(IXAM_BASE_DOMAIN)/"

          - name: JENKINS_GERRIT_PASSWORD
            value: nv#kIaD)nsfk@e
          - name: JENKINS_GERRIT_USERNAME
            value: jenkins
          - name: JENKINS_HOST
            value: jenkins

          - name: INITIAL_ADMIN_PASSWORD
            value: $(GERRIT_HTTP_CREDENTIALS)
          - name: INITIAL_ADMIN_USER
            value: $(LDAP_ADMIN_USERNAME)

          - name: SMTP_CONNECT_TIMEOUT
            value: 10sec
          - name: USER_EMAIL
            value: $(SMTP_USER)
          - name: SMTP_FROM
            value: '"Code Review <$(SMTP_USER)>"'

          - name: NOTEDB_CHANGES_AUTOMIGRATE
            value: "true"

          volumeMounts:
          - name: gerrit-volume
            mountPath: /var/gerrit/review_site
          - name: tz-config
            mountPath: /etc/localtime

        volumes:
        # - name: gerrit-volume
        #   persistentVolumeClaim:
        #     claimName: gerrit-volume
        - name: gerrit-volume
          azureDisk:
            kind: Managed
            diskName: gerrit-volume
            diskURI: /subscriptions/26fb1a24-9c5e-443a-a885-13b488164e73/resourceGroups/MC_ixam-devops_ixam-devops_chinanorth2/providers/Microsoft.Compute/disks/gerrit-volume
        - name: tz-config
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai

# - apiVersion: v1
#   kind: PersistentVolumeClaim
#   metadata:
#     labels:
#       service: gerrit-volume
#     name: gerrit-volume
#   spec:
#     accessModes:
#     - ReadWriteOnce
#     resources:
#       requests:
#         storage: 4Gi
